spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?characterEncoding=utf-8&use=SSL=false
  jpa:
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: 192.168.65.128
    port: 5672
    username: guest
    password: guest
